

from dataclasses import dataclass

@dataclass 
class Data_ingestion_artifact:
    feature_store_file_path:str 
    train_file_path:str 
    test_file_path:str 
    

class DataIngesionArtifact:...
class DataValidationArtifact:...
class DataTransformationArtifact:...
class DataTrainerArtifact:...
class ModelEvaluationArtifact:...
class ModelPusherArtifact:...

